<a href="https://colab.research.google.com/github/houman-nr/vigilant-umbrella/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)

tensor([[0.0013, 0.4168],
        [0.7915, 0.6188]])


In [6]:
print(y)

tensor([[0.7843, 0.7828],
        [0.1352, 0.2416]])


In [11]:
z = torch.rand(2,2)
print(f'muliply two tensors would be like:\nz=torch.mul(x,y):\n{torch.mul(x,y)}')

muliply two tensors would be like:
z=torch.mul(x,y):
tensor([[0.0011, 0.3263],
        [0.1070, 0.1495]])


In [18]:
print(z[1,1].item())

0.9037267565727234
