<a href="https://colab.research.google.com/github/houman-nr/vigilant-umbrella/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)

tensor([[0.0013, 0.4168],
        [0.7915, 0.6188]])


In [ ]:
print(y)

tensor([[0.7843, 0.7828],
        [0.1352, 0.2416]])


In [ ]:
z = torch.rand(2,2)
print(f'muliply two tensors would be like:\nz=torch.mul(x,y):\n{torch.mul(x,y)}')

muliply two tensors would be like:
z=torch.mul(x,y):
tensor([[0.0011, 0.3263],
        [0.1070, 0.1495]])


In [ ]:
print(z[1,1].item())

0.9037267565727234


In [6]:
import torch
import numpy as np
import pandas as pd
import json

with open('SST2_Train.json', 'r') as file:
    loaded_data = json.load(file)
data_df = pd.DataFrame()

list_text, list_label = [], []
for i in range(len(loaded_data)):
    list_text.append(loaded_data[i]['text'])
    list_label.append(loaded_data[i]['label'])
data_df['text'] = pd.Series(list_text)
data_df['label'] = pd.Series(list_label)

data_df.head()

text     label
0  a stirring , funny and finally transporting re...  positive
1  apparently reassembled from the cutting - room...  negative
2  they presume their audience wo n ' t sit still...  negative
3  this is a visually stunning rumination on love...  positive
4  jonathan parker ' s bartleby should have been ...  positive

In [3]:
data_df.shape

(7447, 2)

In [4]:
pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 63.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 38.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 130.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 100.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 37.8 MB/s eta 0:00:00


In [5]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
from transformers import TrainingArguments